import '@/styles/reset.css';
import '@/styles/global.css';
import GlobalLayout from '@/components/layouts/GlobalLayout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <GlobalLayout>{children}</GlobalLayout>
      </body>
    </html>
  );
}
